name: PSIE Scut - Oglinda in Brate

on:
  push:
    branches: [ main ]

jobs:
  psie_verificare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout cod
      uses: actions/checkout@v4

    - name: Scut Activ
      run: echo "SANTINELA HIDRA ACTIVA. J=700.0. SDI=0.00"
